spring.application.name=Cliente
server.port=8081
# =============================================
#  CONEXION A POSTGRESQL (MISMA BD QUE DJANGO)
# =============================================

spring.datasource.url=jdbc:postgresql://localhost:5432/Proyecto-Integrador
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
#  CONFIGURACION JPA / HIBERNATE
#  (Autorizado para crear tablas de carrito/ordenes)
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Para evitar errores de nombres con guiones
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Archivos subidos (fotos de perfil)
app.upload.dir=uploads
spring.web.resources.static-locations=classpath:/static/,file:./uploads/
